language: php

matrix:
  include:
    - php: "7.2"
    - php: "7.3"
    - php: nightly
  allow_failures:
    - php: "7.4"
    - php: nightly

before_script:
  - composer self-update
  - travis_retry composer install --no-interaction

script:
  - vendor/bin/phpunit
